### ISSUE TITLE
Troy's role

### ISSUE THREAD

**Issue by cariluo** [cariluo/cariluo.github.io#7]
Troy's role is not showing up as I expect it to on the page. I see that his role is defined as Haslam and Dewey Professor of Chemistry at _pages/team/_posts/2003-09-01-troy.md, and role is defined on _layouts/member.html, but then it doesn't show up on the page...?

**Comment by mscho527** [comment]
One should add a line here (https://github.com/cariluo/cariluo.github.io/blob/2dbca8c03c478a80ed3c822ee53f34fd274dada8/_pages/team/index.html#L25) and reference `member.role`. I don't have access to my laptop until tomorrow, so if you @cariluo could fix it, please do; otherwise, I can make the fix later

**Comment by cariluo** [comment]
Splendid. Implemented the fix and learned something in the process. Thanks.
